[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }

anyhow = "1.0.72"
clap = "4.3.19"
tracing = "0.1.37"

modules = { path = "../modules" }
